# Generated by Django 3.2.11 on 2022-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fund',
            field=models.IntegerField(default=500),
        ),
    ]
