# Generated by Django 3.2.11 on 2022-03-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='coin_receive',
        ),
    ]
