# Generated by Django 3.2.11 on 2022-03-02 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_rename_amount_payment_coin_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
