# Generated by Django 3.2.11 on 2022-03-03 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_payment_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buying',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.TextField()),
                ('coin_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
