# Generated by Django 3.2.11 on 2022-03-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_auto_20220305_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='fund',
            new_name='balance',
        ),
    ]
