# Generated by Django 3.2.11 on 2022-04-21 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_auto_20220307_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='at_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
